# Generated by Django 4.0.5 on 2022-06-06 08:57

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='이름')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='슬러그')),
                ('order', models.SmallIntegerField(default=0, verbose_name='카테고리 순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='이름')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성 일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정 일')),
                ('thumbnail', apps.core.fields.UUIDImageField(blank=True, null=True, upload_to='uploads/', verbose_name='썸네일')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=140, null=True, verbose_name='설명')),
                ('status', models.SmallIntegerField(choices=[(0, '공개'), (1, '초안'), (2, '비공개'), (3, '일부 공개')], default=1, verbose_name='상태')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-created'],
            },
        ),
    ]
