 # Generated by Django 4.0.5 on 2022-06-11 15:38

from django.db import migrations


def sync_published(apps, schema_editor):
    # migrate from is_user_only to is_hidden
    Post = apps.get_model("posts", "Post")

    instances = []

    for post in Post.objects.all():
        post.published = post.created
        instances.append(post)

    Post.objects.bulk_update(instances, ["published"])


def revert_published(apps, schema_editor):
    # revert from is_hidden to is_user_only

    Post = apps.get_model("posts", "Post")

    instances = []

    for post in Post.objects.all():
        post.created = post.published
        instances.append(post)

    Post.objects.bulk_update(instances, ["created"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_published"),
    ]

    operations = [
        migrations.RunPython(sync_published, revert_published, True),
    ]
